{
	"??????????????????",
	"It is certain",
	"Ask again later",
	"Don’t count on it",
	"Yes?",
	"REDIRECTING...",
	"Try again",
	"UNKNOWN",
	"DEFINITELY",
	"NOH",
	"Yeah",
	"Probably not",
	"Maybe",
	"YOU TELL ME",
	"404 ANSWER NOT FOUND",
	"403 ANSWER FORBIDDEN",
	"HUH??",
	"I don't know",
	"YES",
	"HOW SHOULD I KNOW",
	"WHY WOULD YOU ASK?",
	"MAYBE TOMORROW"
}
